name = "EulerLagrange"
uuid = "e4b6a126-98cc-486b-a68d-c3e5d57f8cc9"
version = "0.4.4"
authors = ["Michael Kraus"]

[deps]
GeometricBase = "9a0b12b7-583b-4f04-aa1f-d8551b6addc9"
GeometricEquations = "c85262ba-a08a-430a-b926-d29770767bf2"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RuntimeGeneratedFunctions = "7e49a35a-f44a-4d26-94aa-eba1b4ca6b47"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
GeometricBase = "0.10, 0.11, 0.12"
GeometricEquations = "0.16, 0.17, 0.18, 0.19, 0.20"
RuntimeGeneratedFunctions = "0.5"
Symbolics = "5.24, 6, 7"
julia = "1.10"

[extras]
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Parameters", "SafeTestsets", "Test"]
